server:
  port: 22222
#  error:
#    path: /error

spring:
  application:
    name: "my_apte4ka"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/my_apte4ka
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
#  resources:
#    static-locations: file:uploads/img/

#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE
#      hibernate: TRACE